version: '3.4'
services:
  jubilantbroccoli:
    image: ${DOCKER_REGISTRY-}jubilantbroccoli
    command: ./../wait-for-postgres.sh db ./jubilantbroccoli
    build:
      context: .
      dockerfile: JubilantBroccoli/Dockerfile
    depends_on:
        - broccoli.db
    ports:
      - "5001:443"
      - "8080:80"  
    restart: always

  jubilantbroccoli.backgroudservice:
    image: ${DOCKER_REGISTRY-}jubilantbroccolibackgroundservice
    command:  ./../wait-for-postgres.sh db ./jubilantbroccoli.backgroudservice
    build:
      context: .
      dockerfile: JubilantBroccoli.BackgroundService/Dockerfile
    deploy:
      resources:
        limits:
            cpus: '0.1'
            memory: 1G
    restart: always
    depends_on:
        - broccoli.db
        - jubilantbroccoli

  broccoli.db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "broccoli"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    container_name: broccoli-postgres
    restart: always