version: '3.4'
services:
  jubilantbroccoli:
    image: ${DOCKER_REGISTRY-}jubilantbroccoli
    build:
      context: .
      dockerfile: JubilantBroccoli/Dockerfile

  broccoli.db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "broccoli"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    container_name: broccoli-postgres
