version: '3.4'
services:
  jubilantbroccoli:
    image: ${DOCKER_REGISTRY-}jubilantbroccoli
    build:
      context: .
      dockerfile: JubilantBroccoli/Dockerfile
    depends_on:
        broccoli.db:
            condition: service_healthy
    ports:
      - "5001:443"
      - "8080:80"  
    restart: always

  jubilantbroccoli.backgroudservice:
    image: ${DOCKER_REGISTRY-}jubilantbroccolibackgroundservice
    build:
      context: .
      dockerfile: JubilantBroccoli.BackgroundService/Dockerfile
    deploy:
      resources:
        limits:
            memory: 1G
    restart: always
    depends_on:
        broccoli.db:
            condition: service_healthy

  broccoli.db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "broccoli"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    container_name: broccoli-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always